name: Build and Deploy to CloudHub 

on:
  push:
    branches: 
      - main
      - dev
  workflow_dispatch:
    
jobs:
  # test:
    # runs-on: ubuntu-latest
    # steps:
    #   - name: Checkout this repo
    #     uses: actions/checkout@v3

    #   - name: Set output
    #     id: branchName
    #     run: echo "name=${GITHUB_REF##*/}" 
        
  call-workflow:
    # Importing a reusable workflow from another repository and branch
    runs-on: ubuntu-latest
    steps:
      - name: set ur
        id: workflow_url
        run: echo url=priyankasingh17/mule-reusable-workflow/.github/workflows/build-and-deploy-${GITHUB_REF##*/}.yml@maim
    # uses: priyankasingh17/mule-reusable-workflow/.github/workflows/build-and-deploy-${GITHUB_REF##*/}.yml@maim
      - name: call flow
        uses: ${{steps.workflow_url.outputs.url}}
    # with:
    # 
