name: Build and Deploy to CloudHub 

on:
  push:
    branches: 
      - main
      - dev
  workflow_dispatch:
    
jobs:
  call-main-workflow:
    if: github.ref == 'refs/heads/main'      
    uses: priyankasingh17/mule-reusable-workflow/.github/workflows/build-and-deploy-main.yml@main
    
  call-dev-workflow:
    if: github.ref == 'refs/heads/dev'      
    uses: priyankasingh17/mule-reusable-workflow/.github/workflows/build-and-deploy-dev.yml@main
     

